config/routes.rb
Rails.application.routes.draw do
  get 'users/:username', to: 'users#show', as: 'user'

  resources :user, only: :show, param: :username do
    member do
      post 'follow', to: 'follows#create'
      delete 'unfollow', to: 'follows#destroy'
    end
  end
  resources :clues
  resources :tweets
  ActiveAdmin.routes(self)
  devise_for :users
  as :user do
  	get "signin" => 'devise/sessions#new'
  	delete "signout" => 'devise/sessions#destroy'
  	get 'signup' => 'devise/registrations#new'
  end
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contactus' => 'pages#contactus'
  get 'clues' => 'pages#clues'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

	def authorized?(action, subject = nil)
		user && user.admin?
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clue.rb
class Clue < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  validates :content, presence: true
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" and "follower" interface
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/sighting.rb
class Sighting < ApplicationRecord
	belongs_to :user
	geocoded_by :address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates
	validates :user, presence: true
	validates :content, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :content, presence: true, length: { maximum: 140 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :clues
  has_many :sightings

  validates :username, presence: true, uniqueness: true, length: { minimum: 6 }
  validates :name, presence: true

  acts_as_followable
  acts_as_follower
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
  	redirect_to root_path, alert: exception.message
  end

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
	end
end

app/controllers/clues_controller.rb
class CluesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /clues
  # GET /clues.json
  def index
@clues = Clue.all
  end

  # GET /clues/1
  # GET /clues/1.json
  def show
    set_clue
  end

  # GET /clues/new
  def new
    @clue = current_user.clues.new
  end

  # GET /clues/1/edit
  def edit
    set_clue
  end

  # POST /clues
  # POST /clues.json
  def create
    @clue = current_user.clues.new(clue_params)

    respond_to do |format|
      if @clue.save
        format.html { redirect_to @clue, notice: 'Clue was successfully created.' }
        format.json { render :show, status: :created, location: @clue }
      else
        format.html { render :new }
        format.json { render json: @clue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clues/1
  # PATCH/PUT /clues/1.json
  def update
    respond_to do |format|
      if @current_user.clues.update(clue_params)
        format.html { redirect_to @clue, notice: 'Clue was successfully updated.' }
        format.json { render :show, status: :ok, location: @clue }
      else
        format.html { render :edit }
        format.json { render json: @clue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clues/1
  # DELETE /clues/1.json
  def destroy
    @clue.destroy
    respond_to do |format|
      format.html { redirect_to clues_url, notice: 'Clue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clue
      @clue = Clue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clue_params
      params.require(:clue).permit(:user_id, :content)
    end
end

app/controllers/follows_controller.rb
class FollowsController < ActionController::Base
  protect_from_forgery with: :exception
	def create
		user = User.find_by(username: params[:username])
		Follow.create(followable: user, follower: current_user)
		redirect_to user_path(user.username), notice: "Successfully followed user"
end

	def destroy
		user = User.find_by(username: params[:username])
		Follow.find(followable: user, follower: current_user).destroy
		redirect_to user_path(user.username), notice: "Successfully unfollowed user"
end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]

  # GET /sightings
  # GET /sightings.json
  def index
    @sightings = Sighting.all
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
  end

  # GET /sightings/new
  def new
    @sighting = Sighting.new
  end

  # GET /sightings/1/edit
  def edit
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(sighting_params)

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:user_id, :address, :latitude, :longitude, :comments)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
    @tweet = current_user.tweets.new(tweet_params)
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to @tweet, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was successfully destroyed.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clues_helper.rb
module CluesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/clues/_form.html.erb
<%= form_for(clue) do |f| %>
  <% if clue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(clue.errors.count, "error") %> prohibited this clue from being saved:</h2>

      <ul>
      <% clue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clues/edit.html.erb
<link href="https://fonts.googleapis.com/css?family=Happy+Monkey|Inconsolata|Indie+Flower|Titillium+Web" rel="stylesheet">
<h1 style="text-align: center; font-family: 'Indie Flower';">Editing Clue</h1>

<p style="text-align: center; font-family: 'Inconsolata'; font-size: 1.25em">Made a mistake? Fix it. We need good information or we all die.</p>

<%= render 'form', clue: @clue %>

<%= link_to 'Show', @clue %> |
<%= link_to 'Back', clues_path %>
<p style="text-align: center;"><img src="http://media.giphy.com/media/XIqCQx02E1U9W/giphy.gif" height="200" width="300"></p>

app/views/clues/index.html.erb
<p id="notice"><%= notice %></p>
<link href="https://fonts.googleapis.com/css?family=Mirza|Space+Mono" rel="stylesheet">
<% if user_signed_in? %>
  <h1 style="font-family: 'Space Mono', monospace; text-align: center; background-color: #DCDCDC"">Clues</h1>

  <table>
    <thead>
      <tr>
        <span style="font-family: 'Mirza', cursive;">
        <th>User</th>
        <th>Content</th></span>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
        <% @clues.each do |clue| %>
          <tr>
            <td><%= clue.user %></td>
            <td><%= clue.content %></td>
            <td><%= link_to 'Show', clue %></td>
            <% if clue.user == current_user %>
              <td><%= link_to 'Edit', edit_clue_path(clue) %></td>
              <td><%= link_to 'Destroy', clue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
        <% end %>
        <% else %>
        <p style="font-size: 3em;"> There's nothing for your to see here.</p>
        <% end %>
    </tbody>
  </table>

  <br>
  <% if user_signed_in? %>
    <p><%= link_to 'New Clue', new_clue_path %></p>
    <p style="text-align: center;"><img src="http://i.giphy.com/MGaacoiAlAti0.gif" height="300" width="400"></p>
  <% else %>
    <p style="text-align: center;"><img src="http://i0.kym-cdn.com/photos/images/newsfeed/001/023/007/f29.png" rel="nofollow"></p>
    <p style="text-align: center;">Page only here to show that work was done. You must be signed in to view app.</p>
<% end %>

app/views/clues/new.html.erb
<link href="https://fonts.googleapis.com/css?family=Happy+Monkey|Titillium+Web" rel="stylesheet">
<h1 style="font-family: 'Titillium Web', sans-serif; text-align: center;">New Clue</h1>

<p style="text-align: center; font-family: 'happy monkey' font-size: 1.5em">Wanna help us find the truth? Good. We're all ears. Let us know what you have found below</p>

<%= render 'form', clue: @clue %>

<%= link_to 'Back', clues_path %>
<p style="text-align: center;"><img src="http://www.reactiongifs.com/r/dgpt.gif" height="200" width="300">

app/views/clues/show.html.erb
<link href="https://fonts.googleapis.com/css?family=Athiti|Happy+Monkey|Inconsolata|Indie+Flower|Lobster|Titillium+Web" rel="stylesheet">
<p id="notice"><%= notice %></p>
<div style="border-style: dotted; text-align: center; background-color: #808080;">
<% if user_signed_in? %>
	<img class="card-img-top" src="http://media.giphy.com/media/jT9Q3YGdORcTC/giphy.gif" height="200" width="180">
		<p style="font-size: .75em; font-family: 'Lobster'">
	  User:
	  <%= @clue.user %>
	</p>

	<p class="card-text;">
	  <h4 style="font-family: 'Titillium Web';">Content:
	  <%= @clue.content %></h4>
	</p>
	</div>
<% if @clue.user == current_user %>
	<%= link_to 'Edit', edit_clue_path(@clue) %> |
<% end %>
	<%= link_to 'Back', clues_path %>
<% end %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Other People's Universes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-dark bg-inverse">
      <div class="container">
        <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
        <ul class="nav navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", contactus_path, class: "nav-link" %>
          <li class="nav-item"><%= link_to "Clues", clues_path, class: "nav-link" %></li>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item float-md-right"><%= link_to "Log out", signout_path, method: :delete, class: "btn btn-primary" %></li>
          <% else %>
            <li class="nav-item float-md-right"><%= link_to "Sign in", signin_path, class: "btn btn-primary"%></li>
            <li class="nav-item float-md-right"><%= link_to "Sign up", signup_path, class: "btn btn-primary" %></li>
            <% end %>
        </ul>
      </div>
    </nav>

    <!-- Flash Message-->
    <% flash.each do |name, message| %>
    <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<head><link href="https://fonts.googleapis.com/css?family=Amatic+SC|Anton|Aref+Ruqaa|Catamaran" rel="stylesheet"></head>

<div class="jumbotron">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>. Feel free to scroll to the bottom to find out more. :)</p>

        <div class="hiddentext"><span style="font-family: 'Aref Ruqaa', serif; font-size: 1.5em"><p>Actually, I lied. You came here for truth and the truth is that you shouldn't blink. They're coming for you because they know. They know you know and I'm sorry. I never should have dragged you into this...</p>

        <p>I heard you can't look into their eyes for very long or you become one of them.</p> 

        <p>They're right... They're right...</p>

        <p>I can't even look at this screen without seeing in the reflection. It's coming for me...</p>

        <p>Run...</p>

        <p>It's... not too late... It's taking over.. But you can make it. You can..lalds;j;jadsfjk;ljkl;ads;rj;jdkas;jk;l
        adl;luadsrlku;adsnf;lkadjfs
        ouaeadjlf;jadf,</p></span>

        <p style="font-family: 'Amatic SC', cursive; font-size: 5em; text-align: right;">WE'RE COMING</p> 
        <p style="font-family: 'Amatic SC', cursive; font-size: 5em; text-align: left;">FOR YOU NOW.</p>
        <p style="font-family: 'Amatic SC', cursive; font-size: 5em; text-align: center;">WE'RE HUNGRY.</p></div>
    </div>
</div>

app/views/pages/contactus.html.erb
<h1>Contact Us</h1>
<link href="https://fonts.googleapis.com/css?family=Oswald|Roboto" rel="stylesheet">
<p>What Up. We In Here.</p>
<p style="font-size: 1.75em; font-family: 'Oswald', sans-serif;">Scott Buendia</p>
<p>Your House</p>
<p>Your Phone Number</p>
<p>I'm not giving you my email</p>
<p style="text-align: center;"><iframe src="//giphy.com/embed/d3fT7K9QrI5IQ" width="200" height="100" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></p>
<p style="text-align: center;"><iframe width="400" height="200" src="https://www.youtube.com/embed/3G9WYmzdrhc" frameborder="0" allowfullscreen></iframe></p>
<p style="font-size: 3em; font-family: 'Oswald', sans-serif; text-align: center;">I'm good at reading people. My secret , I look for the <span style="font-size: 2em">worst</span> in them. <span style="font-size: .25">(Elliot,</span> <span style="font-size: 1.5em">Mr. Robot)</span></p>

app/views/pages/home.html.erb
<head>
    <link href="https://fonts.googleapis.com/css?family=Anton|Aref+Ruqaa" rel="stylesheet">
</head>

<% if user_signed_in? %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
        <h1>Welcome Back!</h1>
        </div>
    </div>   
<% else %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
            
            <h1 style="font-family: 'Anton', sans-serif;">Search For Truth</h1>
            <p>Reality Lies.</p>
            <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
    </div>
</div>
   <% end %>
 <div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Everyone Lies</h2>
            <p>Trust is not something given. It is earned. It is lost. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>tHERE IS NO sPoon</h2>
            <p>Humans are broken. Why do you keep relying on them? </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Truth... Watch Your Back</h2>
            <p><iframe width="300" height="200" src="https://www.youtube.com/embed/V6wPTyUlKAE" frameborder="0" allowfullscreen></iframe></p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>

app/views/sightings/_form.html.erb
<%= form_for(sighting) do |f| %>
  <% if sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :latitude %>
    <%= f.text_field :latitude %>
  </div>

  <div class="field">
    <%= f.label :longitude %>
    <%= f.text_field :longitude %>
  </div>

  <div class="field">
    <%= f.label :comments %>
    <%= f.text_area :comments %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form', sighting: @sighting %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
<h1>Sightings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.user %></td>
        <td><%= sighting.address %></td>
        <td><%= sighting.latitude %></td>
        <td><%= sighting.longitude %></td>
        <td><%= sighting.comments %></td>
        <td><%= link_to 'Show', sighting %></td>
        <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
        <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sighting', new_sighting_path %>
<% end %>

<p style="font-size: 1.5em; text-align: center;">Sight seeing in the USA is awesome.</p>

app/views/sightings/new.html.erb
<h1>New Sighting</h1>

<%= render 'form', sighting: @sighting %>

<%= link_to 'Back', sightings_path %>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @sighting.user %>
</p>

<p>
  <strong>Address:</strong>
  <%= @sighting.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sighting.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sighting.longitude %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @sighting.comments %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

    <%= f.submit class: "btn btn-primary" %>

<% end %>

app/views/tweets/edit.html.erb
<div class="container">
	<h1>Editing Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Show', @tweet %> |
	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
<div class="container">

<h1>Tweets</h1>

<table class="table-inverse">
  <thead>
    <tr>
      <th>User</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.user.email %></td>
        <td><%= tweet.content %></td>
        <td><%= link_to 'Show', tweet %></td>
        <% if tweet.user == current_user %>
          <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
          <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Tweet', new_tweet_path %>
<% end %>
</div>

app/views/tweets/new.html.erb
<div class="container">

	<h1>New Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
	<div class="row">
		<div class="offset-md-2 col-md-8">
		<div class="card car-block">
		<h4 class="card-title"><% @tweet.user.email %></h4>
		<p class="card-text"><% @tweet.content %>
<% if @tweet.user == current_user %>
	<%= link_to 'Edit', edit_tweet_path(@tweet) class: "card-link" %>
	<%= link_to 'Delete', @tweet, method: :Delete, class: "card-link" %>
<% end %>
	<%= link_to 'Back', tweets_path class: "card-link" %>
</div>